server:
  port: 9001
spring:
  application:
    name: kafka
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.99.243.32:3306/geo?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
        queue-capacity: 200
        keep-alive: 60s
      thread-name-prefix: geo-